### PR TITLE
[indi-limesdr] removed limesuite from opensuse

### PR DESCRIPTION
**Pull request by iliaplatone**

### CODE REVIEW

**Comment by iliaplatone** [comment]
That's all, sorry.. I couldn't build on both, so I simply removed the lib

**Comment by jochym** [comment]
Why stretch? The docker image build fine except opensuse. (https://hub.docker.com/r/jochym/indi-docker/builds/)

**Comment by iliaplatone** [comment]
The problem is not with the image itself, but with the library which is not updated enough, so the driver I need to build with limesuite fails building.
I'm sorry for this time spent, but I noticed only now about this issue.

**Comment by jochym** [comment]
Stretch is the last stable debian release. Isn't there any way to build the driver for it?
I would rather leave the lib in - to facilitate work towards this goal. There is no harm in keeping it in except a bit of size increase for the image.

**Comment by iliaplatone** [comment]
wait.. maybe this is possible. It's worth a try

**Pull request closed without merging**
